# Generated by Django 2.2.6 on 2020-07-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmimage',
            old_name='imageName',
            new_name='image_name',
        ),
    ]
