# Generated by Django 2.2.6 on 2020-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20200727_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmimage',
            name='camera_no',
            field=models.IntegerField(default=0),
        ),
    ]
